### PR TITLE
Add generic "RowValueWidget" that just displays the given value 

### PR DESCRIPTION
**Pull request by frmdstryr**
Useful for implementing widgets with custom handlers using onPress. For example, a DatePickerAndroid implementation can be done via:

```jsx

<GiftedForm.RowValueWidget
  title='Date of birth'
  name='dateOfBirth' // mandatory
  displayValue='dateOfBirth'
  image={<Icon name={tk+'-calendar'} size={iconSize} style={styles.icon} />}
  value={this.state.dateOfBirth}
  onPress={() => {
    DatePickerAndroid.open({
      date: (this.state.dateOfBirth)? Date.parse(this.state.dateOfBirth): new Date(),
      maxDate: new Date(),
      mode: 'spinner',
    }).then((r)=>{
      if (r.action !== DatePickerAndroid.dismissedAction) {
                      // Selected year, month (0-11), day
      this.setState({dateOfBirth:`${r.month}/${r.day}/${r.year}`});
    }
    }).catch((code,message)=>console.warn('Cannot open date picker', message));
}}
/>

```

With this widget.

### CODE REVIEW

**Review by cooperka — CHANGES_REQUESTED** [review]
Very generic, I like the concept. Thanks for the PR 👍

Two quick asks: can you please add it to the README, and can you share a screenshot on the PR of what it looks like?

**Comment by frmdstryr** [comment]
output

**Review by cooperka — APPROVED** [review]
Thanks for the quick response. LGTM.

**Comment by Ethan0007** [comment]
@frmdstryr just want to ask where did get the DatePickerAndroid? is this native from rn?

**Pull request merged**
