### PR TITLE
React 16 compatability

### PR DESCRIPTION
**Pull request by aarondancer**
- Use 'prop-types' package instead of `React.PropTypes`
- Use `createReactClass` from `create-react-class` instead of `React.createClass`
- Update some `require` statements to `import`
- Updated dependencies (fixes issues with latest MetroBundler and moment)

### CODE REVIEW

**Review by AleXzpm — APPROVED** [review]

**Comment by aarondancer** [comment]
Anyone want to merge this? I'm sure this is preventing people from upgrading RN.

**Comment by Jonovono** [comment]
PLASE!!!

**Comment by klapperkopp** [comment]
same issue. can anyone please merge? thanks.

**Review by klapperkopp — APPROVED** [review]

**Comment by jterps08** [comment]
@FaridSafi @cooperka can you merge this when you get a chance please?

**Comment by cooperka** [comment]
Tested and verified, thanks for the ping @jterps08. Released in v0.1.1.

**Pull request merged**
